# Generated by Django 4.0.5 on 2022-06-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Name', models.CharField(max_length=1000)),
                ('Email', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('IsActive', models.CharField(max_length=500)),
                ('Roles', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=1000)),
                ('Salt', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='IssuList',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Tags', models.CharField(max_length=500)),
                ('Body', models.CharField(max_length=20000)),
                ('Heading', models.CharField(max_length=20000)),
                ('Email', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Access.login')),
            ],
            options={
                'db_table': 'issuList',
            },
        ),
    ]
