# Generated by Django 4.0.5 on 2022-06-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issulist',
            name='Email',
        ),
    ]
