# Generated by Django 4.0.5 on 2022-06-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0002_remove_issulist_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='IsActive',
        ),
    ]
